### PR TITLE
Change plant and installation to required

### PR DESCRIPTION
**Pull request by Eddasol**

### CODE REVIEW

**Comment by Christdej** [comment]
Remember that changing columns to required will not migrate automatically if the columns are empty in the database.
Please check and update the dev and staging databases to have values in the now empty columns.

**Comment by Eddasol** [comment]
> Remember that changing columns to required will not migrate automatically if the columns are empty in the database. Please check and update the dev and staging databases to have values in the now empty columns.

Checked and there are no empty columns entries for plant and installation

**Review by andchiind — APPROVED** [review]
LGTM

**Pull request merged**
