### PR TITLE
Remove unnecessary icons in header

### LINKED ISSUE #1444: Remove unnecessary icons in Flotilla header
**Describe the improvement you would like to see**
Suggest to remove the icons in the Flotilla header if we do not have specific plans to use them in the near future.

Image

### PR DESCRIPTION
**Pull request by mrica-equinor**
Closes #1444

### CODE REVIEW

**Comment by mrica-equinor** [comment]
image

image

**Comment by prasm313** [comment]
When the dimensions of the screen is under 700px the icon jumps to the middle (see line 15 in Header.tsx). Not sure if any of our devices would be affected by this.

image

**Comment by mrica-equinor** [comment]
> When the dimensions of the screen is under 700px the icon jumps to the middle (see line 15 in Header.tsx). Not sure if any of our devices would be affected by this.
> 
> image

Yeah there was a bit of code that I could have deleted, should be good now :)

**Comment by prasm313** [comment]
Last comment resolved👍

- Would have to scroll to see the "NO" language selector (seems to me that this is because of the header).

- There is no margin for the "NO" on the right.

image

**Comment by mrica-equinor** [comment]
> Last comment resolved👍
> 
> * Would have to scroll to see the "NO" language selector (seems to me that this is because of the header).
> * There is no margin for the "NO" on the right.
> 
> image

Yeah I tested with iPhone XR and didn't notice that the iPhone 12 screen is smaller. The margin left to the platform button was too big for the screen size. I updated this and think it's good now

**Review by oysand — APPROVED** [review]
LGTM

**Pull request merged**
