### PR TITLE
Mission definition page phone-compatibility

### PR DESCRIPTION
**Pull request by prasm313**
**Result**

**Phone**
image

image

**Computer**
image

### CODE REVIEW

**Comment by oysand** [comment]
Should we bundle a fix on the edit dialogue while we are at it? 
image

**Comment by prasm313** [comment]
> Should we bundle a fix on the edit dialogue while we are at it? image

Done in latest commit

**Comment by oysand** [comment]
Remember to rebase away the merge commit

**Review by mrica-equinor — APPROVED** [review]
LGTM :)

**Pull request merged**
