### PR TITLE
Run csharpier to format all files

### PR DESCRIPTION
**Pull request by aestene**

### CODE REVIEW

**Review by Christdej — CHANGES_REQUESTED** [review]
Should we add this to a pipeline? If not every PR is going to have a lot of changes in files not related to the PR.

**Comment by aestene** [comment]
> Should we add this to a pipeline? If not every PR is going to have a lot of changes in files not related to the PR.

Yes, that's the plan but I wanted to see if people wanted to use this first.

**Comment by GodVenn** [comment]
Does this make use of the .editorconfig file? Or does it have its own rules?

**Comment by aestene** [comment]
> Does this make use of the .editorconfig file? Or does it have its own rules?

I think it has its own set of "standard rules". We're following the default now.

**Comment by GodVenn** [comment]
I like the formatting it suggested, although we can also get this by using dotnet format, changing the .editorconfig file.
Do you know if the formatting is based on current C# best practices?
And does it also detect naming conventions, use of 'var' and other more code-related issues?

**Comment by aestene** [comment]
> I like the formatting it suggested, although we can also get this by using dotnet format, changing the .editorconfig file. Do you know if the formatting is based on current C# best practices? And does it also detect naming conventions, use of 'var' and other more code-related issues?

Haven't found any specifics on those things but I like the philosophy they follow: https://prettier.io/docs/en/option-philosophy.html

**Comment by aestene** [comment]
image

**Comment by GodVenn** [comment]
Sounds like a good philosophy, I'm up for trying it!Do we have to make some changes to dotnet format for us to still have rules on naming and such or is it good as-is?

**Comment by aestene** [comment]
I ran these commands https://csharpier.com/docs/IntegratingWithLinters
Although I don't know what effect they have. For now it seems to be working together so I suggest just trying it and see if we get issues and then fix them.

I can add a section to the readme for csharpier. I have added it to the pipeline now.

**Review by Christdej — APPROVED** [review]
GJ

**Pull request merged**
